SET(BPKG_64BIT OFF)
SET(BPKG_DEBUG OFF)

IF (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
    MESSAGE("Building in 64bit")
    SET(BPKG_64BIT ON)
ENDIF ()

IF (${CMAKE_BUILD_TYPE} MATCHES Debug)
    SET(BPKG_DEBUG ON)
ENDIF ()

SET(ANTLR4_JAR_LOCATION "${CMAKE_HOME_DIRECTORY}/packages/tools/antlr4/antlr-4.7.2-complete.jar")

IF (${CMAKE_HOST_SYSTEM_NAME} STREQUAL Windows)
    SET(ENV{BOOST_ROOT} "${CMAKE_HOME_DIRECTORY}/packages/libs/boost-1.70.0-win")
    INCLUDE_DIRECTORIES("${CMAKE_HOME_DIRECTORY}/packages/libs/boost-1.70.0-win/include/boost-1_70")
    LINK_DIRECTORIES("${CMAKE_HOME_DIRECTORY}/packages/libs/boost-1.70.0-win/lib")

    IF (${BPKG_64BIT})
        IF (${BPKG_DEBUG})
            SET(antlr4-runtime_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x64/debug/lib/cmake/antlr4")
            SET(antlr4-generator_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x64/debug/lib/cmake/antlr4")
        ELSE ()
            SET(antlr4-runtime_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x64/release/lib/cmake/antlr4")
            SET(antlr4-generator_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x64/release/lib/cmake/antlr4")
        ENDIF ()
    ELSE ()
        IF (${BPKG_DEBUG})
            SET(antlr4-runtime_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x86/debug/lib/cmake/antlr4")
            SET(antlr4-generator_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x86/debug/lib/cmake/antlr4")
        ELSE ()
            SET(antlr4-runtime_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x86/release/lib/cmake/antlr4")
            SET(antlr4-generator_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-win/x86/release/lib/cmake/antlr4")
        ENDIF ()
    ENDIF ()
ELSEIF (${CMAKE_HOST_SYSTEM_NAME} STREQUAL Linux)
    SET(ENV{BOOST_ROOT} "${CMAKE_HOME_DIRECTORY}/packages/libs/boost-1.70.0-linux")
    INCLUDE_DIRECTORIES("${CMAKE_HOME_DIRECTORY}/packages/libs/boost-1.70.0-linux/include/")
    LINK_DIRECTORIES("${CMAKE_HOME_DIRECTORY}/packages/libs/boost-1.70.0-linux//lib")
    LIST(APPEND Boost_LIBRARIES libboost_filesystem.a
            libboost_regex.a)
    IF (${BPKG_64BIT})
        SET(antlr4-runtime_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-linux/x64/lib64/cmake/antlr4")
        SET(antlr4-generator_DIR "${CMAKE_HOME_DIRECTORY}/packages/libs/antlr4-runtime-cpp-4.7.2-linux/x64/lib64/cmake/antlr4")
    ENDIF ()
ENDIF ()

