name: 'Build hoo'
on:
    push:
        branches: [ master ]
jobs:
    build:
        name: ${{ matrix.os }} Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-2019]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '11'
        - uses: actions/setup-python@v2
          with:
            python-version: '3.6'
        - uses: ilammy/msvc-dev-cmd@v1
        - name: Configure
          run: python .\confighoo.py --build-type=release
        - name: Build
          run: cmake --build %GITHUB_WORKSPACE%\out\x64\release\win32
        - name: Test
          run: cmake --build %GITHUB_WORKSPACE%\out\x64\release\win32 --target test
